### ISSUE TITLE
Easier interface for model vs model, obs vs obs, etc

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#107]
Say the user wants to run model vs obs. They use the script below, which was taken from [here](https://acme-climate.github.io/acme_diags/docs/html/quick-guide-edison.html#running-a-full-diagnostics-suite):
```python
reference_data_path = '/global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/'
test_data_path = '/global/project/projectdirs/acme/acme_diags/test_model_data_for_acme_diags/'

test_name = '20161118.beta0.FC5COSP.ne30_ne30.edison'

sets = ['zonal_mean_xy', 'zonal_mean_2d', 'lat_lon', 'polar', 'cosp_histogram']

# optional settings below
diff_title = 'Model - Obs'

backend = 'mpl'  # 'mpl' is for the matplotlib plots.

results_dir = 'diag_demo'  # name of folder where all results will be stored

multiprocessing = True
num_workers =  24
```

Now if they want to run model vs model **using all of the *default* diags**, they'll just edit the `reference_data_path` in the script above and add something for `reference_name`. This doesn't work, b/c in the default diags (which is made for model vs obs), a single run is like so:
```json
{
"set5": [{
		"sets": ["lat_lon"],
		"case_id": "GPCP_v2.2",
		"variables": ["PRECT"],
		"ref_name": "GPCP_v2.2",
		"reference_name": "GPCP (yrs1979-2014)",
		"seasons": ["ANN", "DJF", "MAM", "JJA", "SON"],
		"regions": ["global"],
		"test_colormap": "WhiteBlueGreenYellowRed.rgb",
		"reference_colormap": "WhiteBlueGreenYellowRed.rgb",
		"diff_colormap": "BrBG",
		"contour_levels": [0.5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16],
		"diff_levels": [-5, -4, -3, -2, -1, -0.5, 0.5, 1, 2, 3, 4, 5]
	}]
}
```

where a run for model vs model should be like so:
```json
{
"set5": [{
		"case_id": "set5_model_to_model",
		"variables": ["TREFHT_LAND"],
		"season": ["ANN", "DJF", "MAM", "JJA", "SON"],
		"contour_levels": [210, 220, 230, 240, 250, 260, 270, 275, 280, 285, 290, 295, 300, 305, 310],
		"diff_levels": [-5, -4, -3, -2, -1, -0.5, -0.2, 0, 0.2, 0.5, 1, 2, 3, 4, 5]
	}]
}
```

---

Hence we need some option to handle the different files. This would be handled via the `datasets` (we will change the name soon) parameter. The options would like `'ACME_model_vs_model'`, `'ACME_obs_vs_obs'`, and `'ACME_model_vs_obs'` (an alias is `'ACME_obs_vs_model'`). These would open files [lat_lon_model_vs_model.json](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/driver/lat_lon_model_to_model.json), [lat_lon_obs_vs_obs.json](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/driver/lat_lon_obs_to_obs.json), and [lat_lon_ACME.json](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/driver/lat_lon_ACME.json) respectively. The names of the files should change and be consistent however.

**Comment by zshaheen** [comment]
@golaz Any ideas on what the parameter name should be, the one that signifies whether the run is model vs model, model vs obs, or obs vs obs. @chengzhuzhang and I are currently thinking `comparison_type` or `run_type`.

**Comment by chengzhuzhang** [comment]
#128 also depends on better support to model vs model run

**Comment by zshaheen** [comment]
Done in 88422b0e060ff9d1729e966f35f55c387063e828, now once @chengzhuzhang finishes her bullet points above, we can close this issue.

**Comment by chengzhuzhang** [comment]
pull request #139 resolves this issue
