### ISSUE TITLE
add acme_diags to acme unified env *high priority*

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#108]
Talked to Renata and Val this morning. We need to prioritize this effort and hopefully have this done by Nov 17th

**Comment by doutriaux1** [comment]
it is already part of acme_diags. You just need to let @xylar know when you need to up a version. Also currently matplotlib is not pinned in acme-unified and I believe you need a pinned version, so you might want to add this as well.

**Comment by chengzhuzhang** [comment]
@doutriaux1 yeah. I just emailed @xylar to see how to set it up

**Comment by doutriaux1** [comment]
@chengzhuzhang it's a matter of updating the acme_diags version in the acme-unified metapackage which I think is still hosted [here](https://github.com/UV-CDAT/conda-recipes/commit/b6e04a2314fa4fa5f6ba7b7f142c75cf5a3880b2) 
But the hard/painful task it to update all machines to reflect the changes.

**Comment by zshaheen** [comment]
It's done: https://github.com/UV-CDAT/conda-recipes/pull/20
