### ISSUE TITLE
Show specific configuration for each diags run as provenance in viewer

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#111]
According to discussion on yesterday's meeting, it will be helpful  to show specific configuration that can reproduce each diags run as provenance in viewer.

**Comment by doutriaux1** [comment]
@chengdang please take a look at: https://github.com/PCMDI/pcmdi_metrics/blob/master/src/python/io/base.py#L59-L148

**Comment by chengzhuzhang** [comment]
Thank you for the reference! I think Chris and Jerry are concerned more about the parameter files to reproduce a run. The system and package information is also a plus though.

**Comment by zshaheen** [comment]
- [ ] Remember to use the `inspect` module when there is a function in the parameters. This will display the code for the function in the metadata.

**Comment by zshaheen** [comment]
Done in  79793c6d92107c03ca5773d49154bc6ac85f804f
