### ISSUE TITLE
obs data information lost in the table in master

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#116]
The variable name was truncated and lost the obs data information. The "row_name" in viewer was changed incorrectly. 
@zshaheen Please hold the release before this issue is solved. Thank you!

Old_table variable format:

![old_table](https://user-images.githubusercontent.com/13056557/33969395-e5707bb6-e021-11e7-8602-c5cf1996963a.png)

The one from master:

![screen shot 2017-12-13 at 4 25 57 pm](https://user-images.githubusercontent.com/13056557/33969430-1db00c44-e022-11e7-820e-7f7cadf37964.png)

**Comment by zshaheen** [comment]
@chengzhuzhang View your old code that was in acme_diags_driver.py [here](https://github.com/ACME-Climate/acme_diags/blob/187c91f1efb6132732ea89a6301d892bdc632fea/acme_diags/acme_diags_driver.py)

**Comment by zshaheen** [comment]
@chengzhuzhang I think I fixed this in 52ac7b8eaf8e612c50622683887e4bf0a75e4799. This was my fault, b/c I didn't notice the change you made when I ported over the code. It should all be good now:

Old code:
![screen shot 2017-12-13 at 8 15 46 pm](https://user-images.githubusercontent.com/4239938/33975454-8a84ba56-e043-11e7-960f-56af27358ad8.png)

Code from 52ac7b8eaf8e612c50622683887e4bf0a75e4799:
![screen shot 2017-12-13 at 8 23 20 pm](https://user-images.githubusercontent.com/4239938/33975459-8fdebd3a-e043-11e7-88c9-6f7c2163eab7.png)

If you can test it and let me know if it's good, that would be great. Then we can release if there aren't any other issues.

**Comment by zshaheen** [comment]
@chengzhuzhang Actually, I fixed more stuff in 42a3d8d4f81f8951ae326ca7484b5aafacea53b2

Before the fix:
![screen shot 2017-12-13 at 9 01 18 pm](https://user-images.githubusercontent.com/4239938/33976327-fc6c06f6-e048-11e7-8aca-5fb74388e9e0.png)


After:
![screen shot 2017-12-13 at 9 01 22 pm](https://user-images.githubusercontent.com/4239938/33976333-0204235a-e049-11e7-9790-51861ff91f4d.png)

I think it's good now. Again, just let me know what's good.

**Comment by chengzhuzhang** [comment]
The fix is as I expected:) thank you for fixing it quickly! I think it is all good.
