### ISSUE TITLE
Table csv links in viewer do not allow changing of directory name

### ISSUE THREAD

**Issue by kaabre** [ACME-Climate/acme_diags#123]
The links aren't relative enough -- they include in the path the results_dir, which means I can't change the name of results_dir post-run without breaking all of the links to the tables.  

Example: link is to "acme_diags_results-2018-01-31_13-51-53/viewer/table-data/ANN_metrics_table.html", whereas the other links are more relative -- one of the pngs links to "[results_dir, doesn't matter what it's called or if it changes]/viewer/zonal/debugging-test/prect-global/ann.html" and the others use similar relative paths.

**Comment by zshaheen** [comment]
@kaabre Thanks for letting us know. We'll get to this asap.

**Comment by zshaheen** [comment]
Done in 587e5af0521493c4264fc0babb927f150d60d980.
