### ISSUE TITLE
Get v0.1b working on macOS

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#13]
The particular nightlies of `vtk-cdat-nox` and `vcs-nox` need to be built on macOS.

**Comment by zshaheen** [comment]
Just have a release with vcs 2.10.2.
Fix the versions numbers to vX.X.X too, so release v0.1.1

**Comment by doutriaux1** [comment]
@zshaheen it will likely be `2.12` not `2.10.2`
