### ISSUE TITLE
Add aliases for options used for sets keyword

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#17]
In addition to supporting `sets = [3, 4, 5, 7]`, we can aliases for 3, 4, 5, and 7.

Maybe have:
 * 3 == "zonal mean line"
 * 4 == "zonal mean height contour"
 * 5 == "lat long contour"
 * 7 == "polar contour"

@chengzhuzhang, what are your thoughts and do you have ideas for keywords that are succinct?
I'll actually implement this, it's trivial.

**Comment by chengzhuzhang** [comment]
@zshaheen This, we can discuss with Chris and Jerry on Tuesday. I will have a list of possible names :)
