### ISSUE TITLE
mpl doesn't support colormap change

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#24]
mpl scripts doesn't support colormap change

**Comment by chengzhuzhang** [comment]
apparently mpl and vcs has different naming system for color maps, some sort of mapping is needed

**Comment by zshaheen** [comment]
@doutriaux1 Charles, are the names of the colormaps different on VCS compared to matplotlib? I would assume so.

 If I remember correctly, Aashish had aliases for the current colormap names. I do not know if these were aliased to mpl ones or something.

**Comment by doutriaux1** [comment]
obviously yes! We do have a function to import an mpl colormap in vcs though... I'll let to other projects implement a function to go the other way we do not have time or funding to support mpl.

**Comment by chengzhuzhang** [comment]
Thank you Charles!

**Comment by golaz** [comment]
Since vcs can import mpl colormaps, let's just use the mpl naming convention.
