### ISSUE TITLE
Change names of the drivers and plotting scripts

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#33]
Instead of setX_driver.py, vcs/set3.py and cartopy/set3.py, have something less obscure.
Some ideas:

* set3_driver.py -> zonal_mean_xy_driver.py
* set4_driver.py -> zonal_mean_2d_driver.py
* set5_driver.py -> lat_lon_driver.py
* set7_driver.py -> polar_driver.py
* cosp_histogram_driver.py is good

And for the plotting
* set3.py -> zonal_mean_xy_plot.py
* set4.py -> zonal_mean_2d_plot.py
* set5.py -> lat_lon_plot.py
* set7.py -> polar_plot.py
* set13 -> cosp_histogram_plot.py

Also have a good interface from going to numbered parameters <-> detailed parameters.

**Comment by zshaheen** [comment]
Your thoughts @chengzhuzhang?

**Comment by chengzhuzhang** [comment]
@zshaheen Yes, that exactly what I mean. The plotting script naming is good to be consistent with driver naming!

**Comment by zshaheen** [comment]
Done in de782fb00f50ce830c411252e4a593f9eaddf9b0
