### ISSUE TITLE
change AMWG json to new obs json

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#40]
ready:
lat_lon_newobs.json
cosp_histogram.json

in progress:
set7,set4,set3 json

**Comment by zshaheen** [comment]
@chengzhuzhang I think this is done.

[This is the old cosp_histogram.json you made](https://github.com/ACME-Climate/acme_diags/blob/b022a0f9651b577c8691f81627f3486fd4f04663/acme_diags/driver/cosp_histogram.json). This file is now called [cosp_histogram_AMWG_default.json](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/driver/cosp_histogram_AMWG_default.json). Any changes should now be done to the new file, cosp_histogram_AMWG_default.json.

[This is the lat_lon_newobs.json you made as well](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/driver/lat_lon_newobs.json). Just edit [lat_lon_AMWG_default.json](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/driver/lat_lon_AMWG_default.json) to your liking.

The other default jsons have been renamed as well. Just search for all 'AMWG_default' in [this directory](https://github.com/ACME-Climate/acme_diags/tree/master/acme_diags/driver)

**Comment by chengzhuzhang** [comment]
@zshaheen 
I wasn't clear of this issue. For now, the package takes AMWG default as default setting for running the diags. But later on we will want to make the new obs as the default jsons to run the package...As soon as I have all other new obs json ready..

I think it will be a good idea to support multiple json files.

**Comment by zshaheen** [comment]
@chengdang So is equivalent to #42? Or did you want multiple default jsons or something like that?

**Comment by chengzhuzhang** [comment]
yes, it's equivalent. I think its a good feature to have multiple json. But it's kind of tricking to have both multiple python scirpts and multiple json scripts...if so, it has to be:
python acme_diags_driver -p p1.py -d j1.json -p p2.py -d j2.json  ?
I mean it has to relate the corresponding json to the python, thoughts?

**Comment by chengzhuzhang** [comment]
wait, 
cosp_histogram_AMWG_default.json should be cosp_histogram_ACME_default.json
lat_lon_newobs.json  should be lat_lon_ACME_degault.json 
The point is to replace the long and updated AMWG default..

**Comment by chengzhuzhang** [comment]
Have a new idea. How about let's have a new parameter '-D' or '-ds' for multiple jsons, which is given some name?

-D AMWG   (which point to multiple AMWG jsons)

-D ACME (should be default, this point to multiple new obs jsons?

@zshaheen

**Comment by zshaheen** [comment]
@chengzhuzhang Hmm, this is a good idea Jill.

I remember Chris talking about this some time ago. Being able to choose between the the different diags like how you exemplified.

What's your input @golaz ?

**Comment by golaz** [comment]
I like the idea of specifying built-in sets as a command line argument. Also, I agree that new sets of plots:

-D ACME

should be the default.

**Comment by zshaheen** [comment]
Done a long time ago.
