### ISSUE TITLE
adding long name for derived variables to be printed in viewer

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#41]

**Comment by zshaheen** [comment]
Finally done, look here: http://aims4.llnl.gov:8000/shaheen2/all_descr/viewer/

![screen shot 2017-08-30 at 10 55 58 am](https://user-images.githubusercontent.com/4239938/29887336-ef8d0d74-8d71-11e7-9140-69bfd24a5930.png)
