### ISSUE TITLE
Update the documentation

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#44]
Some stuff to do:
- [x] Update the examples so the new keywords are used
- [x] Expand on the install instructions
- [x] Update the quick guide to use v1.0.0

**Comment by zshaheen** [comment]
Remember to test the install instructions when CDAT 2.12 is released. This is because we don't want to depend on nightlies and we removed the `-c /label/nightly/uvcdat` from the install instructions.

**Comment by zshaheen** [comment]
Create two installation guides:
1. anaconda
2. for developers (create env from .yml file)

**Comment by zshaheen** [comment]
- [ ] Add `bokeh` channel to installation command: `conda install acme_diags -c acme -c conda-forge -c uvcdat -c bokeh `

**Comment by zshaheen** [comment]
- [ ] Update quick guide to use data from `/p/cscratch`, so the demo can be ran on aims4/acme1.

**Comment by golaz** [comment]
@zshaheen : oh now, I'm afraid you updated the old documentation. The one we should update is the Sphinx one on 'gh-pages'. Instructions on how to update:

https://acme-climate.github.io/acme_diags/docs/html/contributing.html

I issued https://github.com/ACME-Climate/acme_diags/pull/79 to remove old doc files to try to avoid this very problem, but I probably did not explain the reason very well. If you want, I can try to merge your changes myself.

**Comment by zshaheen** [comment]
@golaz, Yes, I saw that. I'll being the process of moving it over to the `gh-pages` branch. I didn't really wanna bother figuring out Sphinx today. But the documentation for the release is pretty much done, but I didn't convert it to Sphinx, hence #73 is still open.
