### ISSUE TITLE
multiple json stopped working properly

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#52]
acme_diags_driver only runs for the last json file attached:
i.e.:
acme_diags_driver.py -p mydiags_v1.py -d driver/lat_lon_ACME.json -d driver/cosp_histogram_AMWG_default.json
only runs for cosp_histogram_AMWG_default.json

This worked on Friday's master though

**Comment by zshaheen** [comment]
There only needs to be one `-d` argument. Using two like in the example above results in the last one begin used. So the correct command would be:
```
acme_diags_driver.py -p mydiags_v1.py -d driver/lat_lon_ACME.json driver/cosp_histogram_AMWG_default.json
```
