### ISSUE TITLE
Order of variable with multiple regions is not in order

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#56]
![screen shot 2017-08-22 at 1 12 00 pm](https://user-images.githubusercontent.com/13056557/29585355-b056cf46-873b-11e7-9e5c-ba7af3abafbd.png)

**Comment by chengzhuzhang** [comment]
i.e.:
we want:
SOLIN polar_S
SOLIN polar_N
FSNTOAC polar_S
FSNTOAC polar_N

......

**Comment by zshaheen** [comment]
Fixed in d8877371ffb32f35823cb813efbf278088246077

![screen shot 2017-08-22 at 3 18 01 pm](https://user-images.githubusercontent.com/4239938/29590205-8cea4ba2-874d-11e7-9999-918e5100b849.png)
