### ISSUE TITLE
HadISST sea ice is not masked out

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#60]
![hadisst_pi-sst-ann-global](https://user-images.githubusercontent.com/15743046/29737179-8f513fcc-89be-11e7-8b8a-694cdea0621e.png)

On the observation panel, sea-ice areas show up with a negative temperature instead of missing values. There might be something wrong in the dataset itself.

**Comment by glpotter** [comment]
I think this is fixed. I put the revised SST in /space1/test_data/acme_diags_observations on aims4. The missing data seem correct and I have plotted with 3 different packages they all have sea ice missing and a few  only slightly below zero values. @golaz @chengzhuzhang

**Comment by glpotter** [comment]
![had_sst_sci](https://user-images.githubusercontent.com/14208252/31048477-98dee866-a5d2-11e7-874c-7991ab9a8f02.png)

**Comment by glpotter** [comment]
The above figure is the ANN for PreIndustrial from the new HadSST data mentioned above. @golaz @chengzhuzhang

**Comment by zshaheen** [comment]
@chengzhuzhang Fixed this in #94
