### ISSUE TITLE
ERA-Interim 500 mb geopotential height

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#61]
ERA-Interim 500 mb geopotential height does not look right:

![era-interim-z3-500-ann-global](https://user-images.githubusercontent.com/15743046/29737260-92426f5c-89bf-11e7-8ea9-114115ad777f.png)

For comparison, the same plot for MERRA looks fine:

![merra2-z3-500-ann-global](https://user-images.githubusercontent.com/15743046/29737268-a663a44c-89bf-11e7-9db0-8f6932dff047.png)

**Comment by golaz** [comment]
From @glpotter via email:

> I found some problems with the ERA-interim reanalysis climatology sets I generated. I have fixed them but not yet replaced the data. The main issues are with the 3D data fields. I have standardized the dates now so all the variables’ climatologies are for 1980-2014. The reason is that we (my NASA job) haven’t updated some of the fields with the latest reanalysis. To be consistent, I chose the more limited period.

**Comment by chengzhuzhang** [comment]
This reminds me that the description in the json file for ERA-interim reanalysis needs to be updated to 1980-2014 if Jerry changed the years climatology is formed.

**Comment by chengzhuzhang** [comment]
@golaz @glpotter 
I tired to reproduce these plots (see below). It seems like ERA-Interim has geopotential height about 1000 meter higher than the model and also MERRA. But the pattern looks OKAY without fixing the color map. All other 3d variables look okay, therefore it is not the interpolation to get the horizonal slice, but I think the particular field Zg has some problem. 
![image](https://user-images.githubusercontent.com/13056557/30224052-16c93fc2-9482-11e7-8ca5-f77c762a4bcd.png)

**Comment by golaz** [comment]
@chengzhuzhang:
Yes, something must be wrong with the 500 hPa Zg ERA-Interim MAM data. Global mean is 64.47 vs 56.59 for MERRA-2.

**Comment by chengzhuzhang** [comment]
@golaz 
I found, not only MAM and 500 mb, Global mean is about 10 hectometer greater in ERA-Interim than the model for each season (ANN, JJA, MAM, SON,DJF, MAM) and each pressure level being analyzed (300, 500mb)

**Comment by golaz** [comment]
@chengzhuzhang : initially everything was bad. Then @glpotter produced a new dataset that was much better, except for MAM. See ANN and MAM figures below.

![era-interim-t-850-ann-global](https://user-images.githubusercontent.com/15743046/30225389-2b7523aa-9487-11e7-833f-b68d76c6c19b.png)
![era-interim-z3-500-mam-global](https://user-images.githubusercontent.com/15743046/30225398-3070a55a-9487-11e7-8156-4901eb6bce39.png)

**Comment by chengzhuzhang** [comment]
@golaz Ah! I'm using outdated data. Interesting that MAM is still bad with the time period 1979-2014. we need to see how the climatology is computed then.

**Comment by golaz** [comment]
@chengzhuzhang : I remember @glpotter mentioning that he had to do something to manipulate the levels separately from the climatology, which might explain why some files are good and one is bad.

**Comment by glpotter** [comment]
I just plotted ERA-Interim MAM from the climatology I generated on AIMS4. It looks fine to me. 
![zg](https://user-images.githubusercontent.com/14208252/30235586-e397aa02-94d7-11e7-8dd9-ca16daa19d49.png)

**Comment by golaz** [comment]
Thanks, @glpotter. We must be using different files. Can you tell us which files you are using and then @chengzhuzhang can make sure that the correct files are on acme1.

**Comment by chengzhuzhang** [comment]
@glpotter Hi Jerry, The numbers in your plot is reasonable. I tried to search for the data on aims4. It seems that I can't relocate the data or figure out the versions by myself...I have to reopen this issue until we have the correct files..

**Comment by chengzhuzhang** [comment]
Put Z3 back to built-in variable list:https://github.com/ACME-Climate/acme_diags/commit/de9a7d2708130d77ec69641659cf72e274300fb7
This issue is related to Zonal mean T: MERRA2 vs ERA-Interim #91
 
![era-interim-z3-500-mam-global](https://user-images.githubusercontent.com/13056557/30931546-dd823be0-a379-11e7-9c0b-e3ded06ad412.png)
