### ISSUE TITLE
CERES-EBAF sign error for FLNS, FLNSC

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#62]
FLNS and FLNSC have the wrong sign for CERES-EBAF:

![ceres_ebaf_surface_v2 8-flns-ann-global](https://user-images.githubusercontent.com/15743046/29737293-0a11520a-89c0-11e7-91d6-8b9be24451ab.png)

**Comment by zshaheen** [comment]
With Chris' PR #67, the error is fixed.

![ceres_ebaf_surface_v2 8-flns-ann-global](https://user-images.githubusercontent.com/4239938/29887709-2bf7a854-8d73-11e7-8980-4fdb56cc1274.png)

![ceres_ebaf_surface_v2 8-flnsc-ann-global](https://user-images.githubusercontent.com/4239938/29887713-2ffbee38-8d73-11e7-8780-675c29b27954.png)
