### ISSUE TITLE
Add CERES-EBAF 2.8 TOA

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#64]
Sine there are large differences between CERES-EBAF TOA 2.8 and 4.0, we should include both datasets.

**Comment by chengzhuzhang** [comment]
Done in commit: fd6cba6210734b61d8a165c77adbd14f9bf8384e
Data are at: /space1/zhang40/obs_for_acme_diags/
Need permission to move data to acme1 @zshaheen

**Comment by chengzhuzhang** [comment]
Thank you @zshaheen for the permission. 
All ceres_ebaf surface and TOA data with v2.8 and v4.0 are available from 
/space1/zhang40/obs_for_acme_diags/   at aims4
and
/p/cscratch/acme/data/obs_for_acme_diags/ accessible from both aims4 and acme1

**Comment by golaz** [comment]
@chengzhuzhang or @zshaheen : the TOA v2.8 files are on aims4 but not acme1. Could one you copy them to

/p/cscratch/acme/data/obs_for_acme_diags/

**Comment by zshaheen** [comment]
@golaz Alright, I'll do that.
Did you want me to move all `ceres_ebaf_surface_v2.8*` files or everything in `/space1/zhang40/obs_for_acme_diags/ `?

**Comment by golaz** [comment]
Can you make sure the /p/cscratch directory mirrors what is in Jill's directory? Something like rsync -av --delete should do.

**Comment by chengzhuzhang** [comment]
@golaz  I accidentally moved the new data to a folder has similar name as obs_for_acme_diags within the same directory...My bad...Now the ceres data are actually moved to obs_for_acme_diags, in a later time, we will have the directory mirror mechanism to sync both directories.

**Comment by zshaheen** [comment]
I fixed this.
