### ISSUE TITLE
New longer names of sets

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#72]
Here are the possible long names for the viewer, as suggested by @golaz 

lat_lon = "Latitude-Longitude contour maps"
zonal_mean_2d = "Pressure-Latitude zonal mean contour plots"
zonal_mean_xy = "Zonal mean line plots"
polar = "Polar contour maps"
cosp_histogram = "CloudTopHeight-Tau joint histograms"

**Comment by zshaheen** [comment]
What's your input @chengzhuzhang?

**Comment by chengzhuzhang** [comment]
All good! 👍

**Comment by zshaheen** [comment]
Fixed in 3f27e7cfc4fda9f3976547c1734aa03ecf803b15

<img width="585" alt="screen shot 2017-09-06 at 10 16 29 am" src="https://user-images.githubusercontent.com/4239938/30125404-27fe788e-92ed-11e7-9fc2-cc06fe5c5eac.png">
