### ISSUE TITLE
Sphinx documentation

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#73]
:(

**Comment by golaz** [comment]
Will try to work on this first, then pass it back to @zshaheen and @chengzhuzhang.

**Comment by zshaheen** [comment]
And then I'll pass it to @chengzhuzhang and @glpotter

**Comment by golaz** [comment]
@zshaheen and @chengzhuzhang: initial port of the documentation is available here

https://acme-climate.github.io/acme_diags

**Comment by chengzhuzhang** [comment]
Thank you @golaz We will take over from here!

**Comment by golaz** [comment]
PR https://github.com/ACME-Climate/acme_diags/pull/79 to remove documentation from master to avoid confusion as to which files should be edited.

**Comment by zshaheen** [comment]
As of 61553c357963960b8718bab40e0e8868a5f31878, all of the documentation is on the `gh-pages` branch, which is created from Sphinx and accessible: https://acme-climate.github.io/acme_diags/
