### ISSUE TITLE
colormaps range handling

### ISSUE THREAD

**Issue by doutriaux1** [ACME-Climate/acme_diags#75]
old vcs colormaps should use range(16,240) (not range(6,240).

See there for code to determine old colormaps and auto range:

https://github.com/UV-CDAT/uvcmetrics/blob/12937a412306488d3b7f37493568f596effd37f5/src/python/frontend/amwg_plotting.py#L32-L73

**Comment by doutriaux1** [comment]
current bad code:
https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/plot/vcs/lat_lon_plot.py#L82

**Comment by zshaheen** [comment]
Fixed, used to be this:
![screen shot 2017-09-07 at 4 18 36 pm](https://user-images.githubusercontent.com/4239938/30189498-161cfbca-93e9-11e7-8cdb-5489bb8fe86a.png)

Now it's this:

![screen shot 2017-09-07 at 4 23 17 pm](https://user-images.githubusercontent.com/4239938/30189500-1beea120-93e9-11e7-9f46-dab7c74db94c.png)
