### ISSUE TITLE
cet_rainbow colormap

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#78]
@golaz 
The `cet_rainbow` colormap is from `colorcet` and not `matplotlib`.
I'm not sure if it can work with vcs.
Is this important for the release, which should be coming soon?

If so, I'll need to work with @doutriaux1 with this.

**Comment by golaz** [comment]
I'm fine releasing without a fully functional vcs back-end; vcs could just default to some other color map.

**Comment by chengzhuzhang** [comment]
@zshaheen I think @golaz is right. Both backends are functional, just vcs plots won't have color maps for some variables that Chris preferred. We can work on adding these to vcs after this release if there are demands.

**Comment by zshaheen** [comment]
@golaz As of now, when you run without any colormaps defined and `vcs`, it breaks. What should the default ref/test/diff colormaps for `vcs` be, since `cet_rainbow` isn't going to work?

**Comment by golaz** [comment]
You can go back to the viridis colormap for ref/test and a red to blue map for diff.

**Comment by zshaheen** [comment]
Running with the default colormaps (`cet_rainbow` for ref/test), which were taken from colorcet, we get:

![screen shot 2017-09-07 at 5 09 22 pm](https://user-images.githubusercontent.com/4239938/30190509-6c39717c-93ef-11e7-9d28-8585ed8bcd27.png)
