### ISSUE TITLE
html5lib isn't working

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#82]
`html5lib` is used for parsing the generated html files from the viewer to add our own customizations.

Using `conda create acme_diags_env -c acme -c conda-forge -c uvcdat` gets `html5lib` from `conda-forge`.

However, the one from this channel doesn't work, so removing it and installing `html5lib` via `conda install html5lib` (which installs from the `anaconda` channel I think) works. 

We shouldn't have to do this. Maybe use another html parser (`lxml`)?

**Comment by golaz** [comment]
If the one-liner doesn't get the right package, can we just have a multi-line installation process that gets html5lib from the channel you want?

(And we were told that getting stuff from conda-forge was safe.)

**Comment by zshaheen** [comment]
No worries Chris, this was fixed in 2492f8e22367478da6f3d5851dec709540ffcb2a and now the installation works with a single command.

This issue is related to what Charles was talking about. We only have one channel that we don't have absolute control over (`conda-forge`). This is bearable, but the more we add, we get issues like this one, where there are numerous versions of a library across different channel. Even something seemingly insignificant as a different ordering of the channels during installation could break things.
