### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#84]
Wouldn't that be nice? Documentation is the icing on the cake, PEP8 the cherry on top.

**Comment by zshaheen** [comment]
This should be doable

**Comment by zshaheen** [comment]
I used this command: `flake8 . --ignore=E402 --max-line-length=140`

**Comment by doutriaux1** [comment]
@zshaheen you should add to the test suite something similar to: https://github.com/UV-CDAT/vcs/blob/master/tests/test_vcs_flake8.py

**Comment by zshaheen** [comment]
@doutriaux1 Beat you to it: https://github.com/ACME-Climate/acme_diags/blob/master/tests/test_flake8.py

**Comment by doutriaux1** [comment]
you're awesome @zshaheen
