### ISSUE TITLE
Final fixes for v1.0.0 release

### ISSUE THREAD

**Issue by zshaheen** [ACME-Climate/acme_diags#87]
@zshaheen
- [x] Fix VCS colorbar issues
- [x] Set the default number of workers to 4 or something similar.

@chengzhuzhang 
- [x] Remove some variables in the default diags (the json files)
- [x] Don't use images with tropics in the README

Someone
- [x] Add a link do the documentation on the README

**Comment by zshaheen** [comment]
- [ ] Fix formatting on Sphinx documentation.

**Comment by zshaheen** [comment]
- [ ] distributed diags wiki page to documentation website
- [ ] add `scheduler_addr` parameter to documentation

**Comment by zshaheen** [comment]
Colormap issue fixed in d1c070d4581e9e1419cb663f1efbbf457386511e, look at the difference plot.

Old way:
<img width="1072" alt="screen shot 2017-09-13 at 11 26 12 am" src="https://user-images.githubusercontent.com/4239938/30394642-85f9c494-9878-11e7-8ffd-235774951018.png">

New way:
<img width="1073" alt="screen shot 2017-09-13 at 11 15 59 am" src="https://user-images.githubusercontent.com/4239938/30394649-8c756e40-9878-11e7-8d95-e37cb7bfe612.png">

**Comment by golaz** [comment]
@zshaheen : are you sure the vcs colormap fix is in and working? I tried today using master and I got a french flag again.

**Comment by zshaheen** [comment]
@golaz Yes, I'm linearly interpolating a mpl colormap, and then passing that into vcs [here](https://github.com/ACME-Climate/acme_diags/blob/master/acme_diags/plot/__init__.py#L77).

First, the instructions below won't be required once we update the code on Anaconda. I haven't bothered to do so since we're so close to a release.
* You might need to delete the `acme_diags` installation located here: `<path_to_anaconda_installation>/anaconda2/envs/env_name/lib/python2.7/site-packages/acme_diags*`
  1. Find the prefix, the anaconda installation: 
     ```
     $ which conda
     /Users/zshaheen/anaconda2/envs/env_name/bin/conda
     ```
     The prefix is: `/Users/zshaheen/anaconda2/envs/env_name`
  2.  Remove it via this: `rm -rf /Users/zshaheen/anaconda2/envs/env_name/lib/python2.7/site-packages/acme_diags*`
  3. Install it again, it should work.
