### ISSUE TITLE
Zonal mean T: MERRA2 vs ERA-Interim

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#91]
Something doesn't look right to me.

Annual zonal mean T vs MERRA2:

![merra2-t-ann-global](https://user-images.githubusercontent.com/15743046/30877893-0472a87c-a2b0-11e7-9e5b-ecdcc03f9ff9.png)

And vs ERA-Interim:

![era-interim-t-ann-global](https://user-images.githubusercontent.com/15743046/30877902-0c2ea2be-a2b0-11e7-9fec-c6d1ec858bb7.png)

**Comment by chengzhuzhang** [comment]
Hi @golaz 
Would you specify which area is problematic? Is it that the ERA-interim doesn't have topography as MERRA2 and Model?

**Comment by golaz** [comment]
Looking at the difference plots near 300 mb and the equator. According to MERRA2, the model has a cold bias of 5 K; according to ERA-Interim a warm bias of 5 K. Do the two reanalyses really differ by 10 K in that region? Maybe @glpotter has some insight.

**Comment by chengzhuzhang** [comment]
With Jerry's corrected data, ERA-Interim has much warmer tropical air temperature around 300 mb, about 7K warmer. Which should be more consist with the MERRA2. I moved the new ERA-Interim data to:
/p/cscratch/acme/data/obs_for_acme_diags

This should solve the Zg problem too. Will post the test results here.


![era-interim-t-ann-global](https://user-images.githubusercontent.com/13056557/30928511-ad734fb0-a370-11e7-8145-d79ef0913a63.png)

**Comment by chengzhuzhang** [comment]
New run with updated ERA-Interim: http://aims4.llnl.gov:8000/zhang40/acme_diags_v1_new_ERA/viewer/

New ERA interim Data need  to be also copied to NERSC edison. @golaz Would you please give me permission to /global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/ ?

**Comment by golaz** [comment]
I changed the permissions to group writable.

**Comment by chengzhuzhang** [comment]
Data also updated on NERSC.
