### ISSUE TITLE
conda installation results in inconsistent versions of mpl

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#93]
Installing ACME Diags with conda results in inconsistent versions of Matplotlib.

Standard instructions on acme1:

`conda create -n acme_diags_env -c acme -c conda-forge -c uvcdat acme_diags`
`matplotlib                2.0.2                    py27_2    conda-forge`

Installing as part of [processflow](https://acme-climate.github.io/acme_processflow/docs/html/installation.html) on acme1:

`conda create -n workflow -c acme -c conda-forge -c uvcdat  -c lukasz processflow`
`matplotlib                1.5.3               np113py27_8    conda-forge`

Standard instructions on Edison:

`conda create -n acme_diags_env -c acme -c conda-forge -c uvcdat acme_diags`
`matplotlib                1.5.3               np113py27_8    conda-forge`

**Comment by zshaheen** [comment]
Okay, I'll get to this.

Running `conda create -n acme_diags_env -c acme -c conda-forge -c uvcdat acme_diags` on my Mac resulted in `    matplotlib 2.0.2-py27_2 conda-forge`

**Comment by golaz** [comment]
In the processflow environment on acme1, I tried to manually install version 2.0.2:

```
source activate workflow
conda install -c conda-forge matplotlib=2.0.2

Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib 2.0.2*
  - uvcdat -> vistrails ==2.12 -> pyqt 4.11.3 -> qt 4.8.6
  - uvcdat -> vistrails ==2.12 -> pyqt 4.11.3 -> sip 4.16.5
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by zshaheen** [comment]
Try: 
`conda create -n acme_diags_env -c acme -c conda-forge -c uvcdat acme_diags --copy`

Note the `--copy`

**Comment by golaz** [comment]
@zshaheen: Tried on NERSC Edison using the `--copy` option. It seems to work as the conda environment now includes matplotlib v2.1.

Should we always use  `--copy`? If so, you can update the ACME Diags and Processflow documentation accordingly and then close this ticket.

**Comment by zshaheen** [comment]
@golaz Yeah, it seems like it. `--copy` just prevents symlinks from the root environment by installing everything in the directory of the new environment. Maybe the root environment already had a version of matplotlib?

This was actually @chengzhuzhang's idea, so thanks Jill!

Once I update the documentation, I'll close this ticket.

**Comment by zshaheen** [comment]
Since we now use `yml` files to do the installation, this isn't an issue anymore. But this probably still doesn't work. Until we implement #102, we'll never know...
