### ISSUE TITLE
Problem with SST plot using v0.4 data

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#94]
@tangq provided me some v0.4 climatology data for comparison to v1. The data is under

`/global/cscratch1/sd/tang30/ACME_simulations/B1850C5_ne30_v0.4/pp/clim_rgr/0178-0197`

The SST plot from ACM Diags does not look right. The masking of model data is not working properly and the RMSE is way off: 6.37 when it should be near 1.

![hadisst_pi-sst-ann-global](https://user-images.githubusercontent.com/15743046/31036236-28c6fcce-a520-11e7-99b2-1c44d6cb179e.png)

**Comment by glpotter** [comment]
It looks to me like you don’t have the updated HADISSTs 

Jerry


Gerald L. (Jerry) Potter Ph.D.
Data and Analysis Consultant
Phone: 707 315-8314
email: jerry.potter@gmail.com

**Comment by chengzhuzhang** [comment]
the masking is not functioning correctly for v0.4 data somehow. Min SST is -273.15. it's problematic. I will have to look at the data.

**Comment by glpotter** [comment]
It’s probably something I did. I’ll  fix it by Monday

**Comment by glpotter** [comment]
![had_sst_sci](https://user-images.githubusercontent.com/14208252/31048517-474d36c8-a5d3-11e7-96b5-20b99c0011cc.png)
This is a plot of the ANN HADSST from the corrected HADSST. I though this data was in the new reference data. Apparently not. It is located in:
 /space1/test_data/acme_diags_observations

**Comment by chengzhuzhang** [comment]
@glpotter  Hey Jerry, no worries. I just moved the new SST data with correct sea ice mask to both ACME1 and Nersc. The problem is for the model plot not obs.  The mask did apply correctly to v0.4 model data.

**Comment by chengzhuzhang** [comment]
Checked 0.4 model data. The problem is that it has both TS and SST as outputs. And SST is problematic. Note that minimum SST is 0 K
![screen shot 2017-09-30 at 9 25 22 pm](https://user-images.githubusercontent.com/13056557/31051757-db1aa7c6-a625-11e7-8312-d56a5b209d00.png)

**Comment by chengzhuzhang** [comment]
Solution: https://github.com/ACME-Climate/acme_diags/commit/8f954aaca7cd8e213efc35a1170d5ff79dcd0b26

Changed the order of entries for derived variable 'SST' to accommodate bad old SST output: put masked 'TS' before 'SST'

@golaz Please let me know if this works..

**Comment by zshaheen** [comment]
I fixed this.
