### ISSUE TITLE
Gracefully ignore variables that are not present

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_diags#95]
If a model variable cannot be found, ACME Diags will fail. It might be better instead if ACME Diags just skipped the particular plots for which the variables are missing. 

I ran into this issue when trying to plot v0.4 data that did not include any COSP variables. I ended up creating a custom JSON file to get around the problem. But that may be too much to ask for the typical user.

**Comment by golaz** [comment]
@chengzhuzhang and @zshaheen : can we make fixing this a priority? I was trying to generate figures for a new experiments that was run without COSP and ACME Diags just fails. This makes ACME Diags look bad. It's probably would be quite easy to just skip over plots instead of failing.

**Comment by zshaheen** [comment]
@golaz Yes we can. This shouldn't be too bad to fix, since we purposefully made it do that when a variable is not there.

**Comment by chengzhuzhang** [comment]
Test results for FCT2 run which ignores the non-existed variables and variables can't be plotted. @golaz 
http://aims4.llnl.gov:8000/zhang40/acme_diags_v1_FCT2/viewer/
