### ISSUE TITLE
Convert default json files to cfg files

### ISSUE THREAD

**Issue by chengzhuzhang** [ACME-Climate/acme_diags#97]
Cfg files has less restrictive format and easier to comprehend by the users. It is the new format being recommended and documented in the software. We should convert all built in json files to cfg accordingly

**Comment by zshaheen** [comment]
What to do:
- [ ] First allow cfg files to have the same title.
- [ ] Convert all model vs obs to cfg
- [ ] Then, make new model vs model (and obs vs obs if time permits) cfg files.

**Comment by zshaheen** [comment]
Support for multiple files with the title `[#]` done in [`47971e8`](https://github.com/UV-CDAT/cdp/commit/47971e8dc24a4a9ea8da73d8c14fe43352b5864b) of cdp.

**Comment by zshaheen** [comment]
Completely done in e1b42c086d326e8955b62bad760da468f16d8f6d.
